### ISSUE TITLE
hi  thank you for share your project. i have a question is that how to get the 9 point(like below)in .xml file 

### ISSUE THREAD

**Issue by chenyuyi94** [severin-lemaignan/meuhmeuh-detector#1]
<image file='2016-05-19-205638.jpg'>
    <box top='186' left='766' width='233' height='199'>
      <part name='0' x='778' y='255'/>
      <part name='1' x='923' y='225'/>
      <part name='2' x='832' y='282'/>
      <part name='3' x='882' y='279'/>
      <part name='4' x='846' y='257'/>
      <part name='5' x='854' y='255'/>
      <part name='6' x='851' y='313'/>
      <part name='7' x='902' y='359'/>
      <part name='8' x='895' y='374'/>
      <part name='9' x='872' y='379'/>
    </box>

i want to know how to get the (x,y) cordination ?
could you please to tell me if you have notice my question.

**Comment by severin-lemaignan** [comment]
@chenyuyi94 thank you for your interest. This repository contains old code, and is not maintained. You'll easily find better examples/starting point on the dlib website.
